# pylint: disable=missing-module-docstring,missing-class-docstring,missing-function-docstring

from __future__ import annotations


class Presets:
    # pylint: disable=too-few-public-methods

    @staticmethod
    def get(
        key: str | None,
        cat1: str | None,
        cat2: str | None,
        value1: str | None,
        value2: str | None,
    ) -> list:
        presets = {
            "Cat1, Value1": [
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": cat1,
                        "y": {"set": value1, "range": {"min": None, "max": None}},
                        "color": None,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Column Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": cat1,
                        "y": {
                            "set": [cat1, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": value1,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Waterfall",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": value1,
                        "y": {"set": cat1, "range": {"min": None, "max": None}},
                        "color": None,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "vertical",
                    },
                    "chart": "Bar Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "circle",
                        "x": cat1,
                        "y": {"set": value1, "range": {"min": None, "max": None}},
                        "color": None,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Lollipop",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "circle",
                        "x": cat1,
                        "y": {"set": cat1, "range": {"min": None, "max": None}},
                        "color": value1,
                        "lightness": None,
                        "size": value1,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Correlogram",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "area",
                        "x": cat1,
                        "y": {"set": value1, "range": {"min": None, "max": None}},
                        "color": None,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Area Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "line",
                        "x": cat1,
                        "y": {"set": value1, "range": {"min": None, "max": None}},
                        "color": None,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Line Chart",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "rectangle",
                        "x": [cat1, value1],
                        "y": {"set": None, "range": {"min": None, "max": None}},
                        "color": cat1,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "vertical",
                    },
                    "chart": "Pie Chart",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "rectangle",
                        "x": cat1,
                        "y": {"set": value1, "range": {"min": None, "max": None}},
                        "color": None,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Polar Column Chart",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "rectangle",
                        "x": value1,
                        "y": {"set": cat1, "range": {"min": "-50%", "max": None}},
                        "color": None,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "vertical",
                    },
                    "chart": "Radial Bar Chart",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "rectangle",
                        "x": [cat1, value1],
                        "y": {"set": None, "range": {"min": "-200%", "max": "100%"}},
                        "color": cat1,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "vertical",
                    },
                    "chart": "Donut Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": None,
                        "y": {"set": None, "range": {"min": None, "max": None}},
                        "color": cat1,
                        "lightness": None,
                        "size": [cat1, value1],
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Treemap",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "circle",
                        "x": None,
                        "y": {"set": None, "range": {"min": None, "max": None}},
                        "color": cat1,
                        "lightness": None,
                        "size": value1,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Bubble Chart",
                },
            ],
            "Cat1, Value1, Value2": [
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": [cat1, value1],
                        "y": {"set": value2, "range": {"min": None, "max": None}},
                        "color": None,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Mekko",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "circle",
                        "x": value1,
                        "y": {"set": value2, "range": {"min": None, "max": None}},
                        "color": None,
                        "lightness": None,
                        "size": None,
                        "noop": cat1,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Scatter Plot",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "rectangle",
                        "x": [cat1, value1],
                        "y": {"set": value2, "range": {"min": None, "max": None}},
                        "color": cat1,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Variable Radius Pie Chart",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "circle",
                        "x": value1,
                        "y": {"set": value2, "range": {"min": None, "max": None}},
                        "color": None,
                        "lightness": None,
                        "size": None,
                        "noop": cat1,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Polar Scatter",
                },
            ],
            "Cat1, Cat2, Value1": [
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": [cat1, cat2],
                        "y": {"set": value1, "range": {"min": None, "max": None}},
                        "color": cat1,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Grouped Column Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Stacked Column Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": True,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Splitted Column Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "stretch",
                        "orientation": "horizontal",
                    },
                    "chart": "100% Stacked Column Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": value1,
                        "y": {"set": [cat1, cat2], "range": {"min": None, "max": None}},
                        "color": cat1,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "vertical",
                    },
                    "chart": "Grouped Bar Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": [cat2, value1],
                        "y": {"set": cat1, "range": {"min": None, "max": None}},
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "vertical",
                    },
                    "chart": "Stacked Bar Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": [cat2, value1],
                        "y": {"set": cat1, "range": {"min": None, "max": None}},
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": True,
                        "align": "none",
                        "orientation": "vertical",
                    },
                    "chart": "Splitted Bar Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": [cat2, value1],
                        "y": {"set": cat1, "range": {"min": None, "max": None}},
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "stretch",
                        "orientation": "horizontal",
                    },
                    "chart": "100% Stacked Bar Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "area",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Stacked Area Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "area",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "stretch",
                        "orientation": "horizontal",
                    },
                    "chart": "100% Stacked Area Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "area",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": True,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Splitted Area Chart - Ridgeline Plot",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "area",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "center",
                        "orientation": "horizontal",
                    },
                    "chart": "Stream Graph",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "area",
                        "x": [cat2, value1],
                        "y": {"set": cat1, "range": {"min": None, "max": None}},
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "center",
                        "orientation": "vertical",
                    },
                    "chart": "Stream Graph Vertical",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "area",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": True,
                        "align": "center",
                        "orientation": "horizontal",
                    },
                    "chart": "Violin Graph",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "area",
                        "x": [cat2, value1],
                        "y": {"set": cat1, "range": {"min": None, "max": None}},
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": True,
                        "align": "center",
                        "orientation": "vertical",
                    },
                    "chart": "Violin Graph Vertical",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "line",
                        "x": cat1,
                        "y": {"set": value1, "range": {"min": None, "max": None}},
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Line Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "line",
                        "x": value1,
                        "y": {"set": cat1, "range": {"min": None, "max": None}},
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "vertical",
                    },
                    "chart": "Vertical Line Chart",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "rectangle",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Polar Stacked Column Chart",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "area",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Polar Area Chart",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "rectangle",
                        "x": [cat2, value1],
                        "y": {"set": cat1, "range": {"min": "-50%", "max": None}},
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "vertical",
                    },
                    "chart": "Radial Stacked Bar Chart",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "rectangle",
                        "x": [cat1, value1],
                        "y": {"set": cat2, "range": {"min": "-50%", "max": None}},
                        "color": cat1,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "stretch",
                        "orientation": "vertical",
                    },
                    "chart": "Nested Donut Chart",
                },
                {
                    "config": {
                        "coordSystem": "polar",
                        "geometry": "area",
                        "x": cat1,
                        "y": {
                            "set": [cat2, value1],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "min",
                        "orientation": "horizontal",
                    },
                    "chart": "Polar Stacked Area",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": cat1,
                        "y": {"set": cat2, "range": {"min": None, "max": None}},
                        "color": value1,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Heat Map Gradient",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": cat1,
                        "y": {"set": cat2, "range": {"min": None, "max": None}},
                        "color": None,
                        "lightness": value1,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Heat Map",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "circle",
                        "x": None,
                        "y": {"set": None, "range": {"min": None, "max": None}},
                        "color": cat1,
                        "lightness": None,
                        "size": [cat2, value1],
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Stacked Bubble Chart",
                },
            ],
            "Cat1, Cat2, Value1, Value2": [
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": [cat1, value1],
                        "y": {
                            "set": [cat2, value2],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Stacked Mekko Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": [cat1, value1],
                        "y": {
                            "set": [cat2, value2],
                            "range": {"min": None, "max": None},
                        },
                        "color": cat2,
                        "lightness": None,
                        "size": None,
                        "noop": None,
                        "split": False,
                        "align": "stretch",
                        "orientation": "horizontal",
                    },
                    "chart": "Marimekko Chart",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "circle",
                        "x": value1,
                        "y": {"set": value2, "range": {"min": None, "max": None}},
                        "color": cat1,
                        "lightness": None,
                        "size": None,
                        "noop": cat2,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Scatter Plot",
                },
                {
                    "config": {
                        "coordSystem": "cartesian",
                        "geometry": "rectangle",
                        "x": None,
                        "y": {"set": None, "range": {"min": None, "max": None}},
                        "color": cat1,
                        "lightness": value2,
                        "size": [cat2, value1],
                        "noop": None,
                        "split": False,
                        "align": "none",
                        "orientation": "horizontal",
                    },
                    "chart": "Stacked Treemap",
                },
            ],
        }
        return presets.get(str(key), [])
